sudo: required
dist: trusty
language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - example.com
    - local.example.com
    - production.example.com
    - www.example.com
before_install:
  - rvm use 1.9.3
  - gem install bundler
  - echo "Install NPM dependencies"
  - npm install -g bower
  - npm install
  - echo "Mock test project"
  - $PWD/bin/mock
  - echo "Move mock project to /vagrant for end-user tests"
  - sudo mv $PWD/temp /vagrant
  - ln -s /vagrant $PWD/temp
  - echo "Copying local Evolution WordPress as dependency"
  - rm -rf /vagrant/bower_components/evolution-wordpress
  - cp -RP $PWD /vagrant/bower_components/evolution-wordpress/
  - echo "Provision server"
  - sudo cp $PWD/.travis.provision.bin $PWD/bin/provision
  - sudo chmod +x $PWD/bin/provision
  - sudo $PWD/bin/provision
  - sudo chown -Rf $USER:$USER $HOME/.ansible
  - echo "Mocking vagrant binary"
  - sudo cp $PWD/.travis.vagrant.bin /bin/vagrant
  - sudo chmod +x /bin/vagrant
  - ssh-keyscan -H production.example.com >> $HOME/.ssh/known_hosts
  - ssh-keyscan -H www.example.com >> $HOME/.ssh/known_hosts
  - ssh-keyscan -H example.com >> $HOME/.ssh/known_hosts
  - curl -sS https://getcomposer.org/installer | php
install:
  - echo "Install Composer dependencies"
  - php composer.phar install --dev
script:
  - ./vendor/bin/phpunit
  - npm test
